config/routes.rb
Rails.application.routes.draw do
  get 'websites/index'

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root 'websites#index'

  match 'websites/display', to: 'websites#display', via: [:get]

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/pdf.rb
class Pdf
  def self.generate_pdf(user_name, tweets, git_repos, rubygems)
  	Prawn::Document.new do
  		text "Twitter, Github and RubyGems Records", :size => 20, :style => :bold, align: :center, :color => "#663333"
  		move_down(30)

  		text "User : #{user_name}".titleize, :size => 15, :style => :bold, :color => "#0066FF"
  		move_down(20)

  		text "Twitter Details", :style => :bold
  		move_down(10)

  		c = 0
  		if !tweets.blank?
  		  tweets = tweets[0..9].map do |t|
  		    t_table = make_table([["#{t.text}"]], :column_widths => [500])
  		    t_table.draw
  		  end
  		else
  		  text "No records found..."
  		end
  		move_down(25)

  		text "Git Repo Details", :style => :bold
  		move_down(10)

  		c = 0
  		if !git_repos.blank?
  		  git_repos = git_repos.map do |g|
  		    text "#{c+=1}. #{g.name}"
  		  end
  		else
  		  
  		end

  		move_down(25)

  		text "Ruby Gems Details", :style => :bold
  		move_down(10)

  		c = 0
  		if !rubygems.blank?
  		  rubygems = rubygems.map do |r|
  			text "#{c+=1}. #{r["name"]}"
  		  end
  		else
  		  text "No records found..."
  		end

  		move_down(35)
  		text "Copyright © 2015 · All Rights Reserved · Peter", :size => 10, :style => :bold, :color => "#FF0000"

  	end.render
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/website.rb
class Website
  def self.normolize_tweets(user_name)
  	begin
  	  tweets = $twitter.user_timeline("#{user_name}")
      raise "Error: no responses!" if tweets.blank?
  	  return tweets
  	rescue => e
  	  Rails.logger.info "Error occurs while gathering tweets #{e.class} - #{e.message}"
  	  return nil
  	end
  end

  def self.normolize_git_repos(user_name)
  	begin
  	  git_repos = $github.repos.list user: "#{user_name}"
  	  raise "Error: no responses!" if git_repos.body.blank? 
      return git_repos
  	rescue => e
      Rails.logger.info "Error occurs while gathering git repos #{e.class} - #{e.message}"
  	  return nil
  	end
  end

  def self.normolize_ruby_gems(user_name)
  	begin
  	  rubygems = Gems.gems("#{user_name}")
  	  raise "Error: No user found!" if rubygems.include?("Owner could not be found") || rubygems.blank?
  	  return rubygems
  	rescue => e
  	  Rails.logger.info "Error occurs while gathering rubygems #{e.class} - #{e.message}"
  	  return nil
  	end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  
  #-> Prelang (user_login:devise)
  def require_user_signed_in
    unless user_signed_in?

      # If the user came from a page, we can send them back.  Otherwise, send
      # them to the root path.
      if request.env['HTTP_REFERER']
        fallback_redirect = :back
      elsif defined?(root_path)
        fallback_redirect = root_path
      else
        fallback_redirect = "/"
      end

      redirect_to fallback_redirect, flash: {error: "You must be signed in to view this page."}
    end
  end

end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  include ApplicationHelper

  def new
    super
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  include ApplicationHelper

  def create
    super
  end

  def new
    super
  end

  def edit
    super
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  include ApplicationHelper

  def create
    super
  end

  def new
    super
  end
end

app/controllers/websites_controller.rb
class WebsitesController < ApplicationController
	def index
	end

  # method to fetch Twitter, Git and RubyGems records
  def display
  	@user_name 	= "#{params[:user_name]}" 

  	# Return all tweets owned by the user.
  	@tweets     = Website.normolize_tweets(@user_name) # Error handling for tweets

  	# Return all repos owned by the user.
  	@git_repos  = Website.normolize_git_repos(@user_name) # Error handling for git repos

  	# Return all gems owned by the user.
  	@rubygems  	= Website.normolize_ruby_gems(@user_name) # Error handling for ruby gems

  	# for PDF generation
  	respond_to do |format|
	    format.html
	    format.pdf do
		    pdf = Prawn::Document.new
		    send_data Pdf.generate_pdf(@user_name, @tweets, @git_repos, @rubygems), filename: 'web_records.pdf', type: 'application/pdf'
	    end
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/websites_helper.rb
module WebsitesHelper
end

app/views/elements/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "Website Records", defined?(root_path) ? root_path : "#", class: "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <!-- <div class="collapse navbar-collapse" id="navbar-collapse-1">
    <ul class="nav navbar-nav">
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if defined?(Devise) %>
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit Account", edit_user_registration_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
      <% end %>
    </ul>
  </div> -->
  <!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WebRecords</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<meta name="viewport" content="width=device-width, initial-scale=1"/></head>
<body>
<%= render partial: "elements/navbar" %>
<%= bootstrap_flash %>


<%= yield %>

</body>
</html>

app/views/websites/display.html.erb
<% if !@user_name.blank? %>
	<h3>Records of '<%= "#{@user_name}".capitalize %>'</h4>
	<br>

	<h4><u>Twitter Records</u></h4>

	<table>
	<% count = 0 %>
	<% unless @tweets.nil? %>
		<% @tweets[0..9].each do |tweet| %>
			<tr>
			  <td><%= count += 1 %>.
			  <td><%= tweet.text %></td>
			</tr>
		<% end %>
	<% else %>
		<strong><%= "Oooooh...No records found" %></strong>
	<% end %>
	</table>


	<br>
	<h4><u>Github Records</u></h4>

	<table>
	<% count = 0 %>
	<% unless @git_repos.nil? %>
		<% @git_repos.each do |gitrepo| %>
			<tr>
			  <td><%= count += 1 %>.
			  <td><%= gitrepo.name %></td>
			</tr>
		<% end %>
	<% else %>
		<strong><%= "Mehhh...No records found" %></strong>
	<% end %>
	</table>

	<br>
	<h4><u>Rubygems Records</u></h4>

	<table>
	<% count = 0 %>
	<% unless @rubygems.nil? %>
		<% @rubygems.each do |rubygem| %>
			<tr>
			  <td><%= count += 1 %>.
			  <td><%= rubygem["name"] %></td>
			</tr>
		<% end %>
	<% else %>
		<strong><%= "Whooo...No records found" %></strong>
	<% end %>
	</table>

<% if !@tweets.nil? || !@git_repos.nil? || !@rubygems.nil? %>
	<br>
	&emsp;<%= link_to 'Download PDF', websites_display_path(:pdf, :user_name => "#{@user_name}"), class: "btn btn-primary"%>
	<br><br>
<% end %>

<% else %>
	<strong><%= "Oops...No user found!" %></strong>
<% end %>

app/views/websites/index.html.erb
<h4>Welcome!</h4>
<br>

<div>
  <%= form_tag("/websites/display", method: "get") do %>
  <%= label_tag(:user_name, "Search for ") %>
  <%= text_field_tag(:user_name, nil, :size=> 50, :placeholder => "User name goes here.....") %>
  <%= submit_tag("Submit", class: "btn btn-primary") %>
  <% end %>
</div>

<a href="http://localhost:3000/job_seekers/register/Manpower-Employer/customer-service-representative?return_to=/jobs/Manpower-Employer/customer-service-representative/enroll?enroll=true" target="_blank" style="font-weight:bold;">To get a step ahead of the competition for this job Click Here</a>
<!-- <base target='_blank' /> -->

<!-- <iframe src="http://localhost:3000/job_seekers/register/Manpower-Employer/customer-service-representative?return_to=/jobs/Manpower-Employer/customer-service-representative/enroll?enroll=true&linkTarget=_blank"> Click Here </iframe> -->

<!-- <a href="http://localhost:3000/job_seekers/register/">link</a> -->
<!-- 
<p>
<a href="http://localhost:3000/job_seekers/register/" target="vidframe">Click here.....</a>
</p>



<iframe name="vidframe" id="vidframe" src="" width='250px' height='250px'></iframe> -->